### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by OlgaYubil** [victordesyatkin/slider#3]
![GIF 19 05 2021 12-15-55](https://user-images.githubusercontent.com/82147736/118795981-d3f28b00-b8a3-11eb-9199-75a0fe1d3cf0.gif)

**Comment by OlgaYubil** [comment]
![GIF 19 05 2021 12-20-04](https://user-images.githubusercontent.com/82147736/118796171-0603ed00-b8a4-11eb-892f-a7d1f00bed50.gif)

**Comment by OlgaYubil** [comment]
![GIF 19 05 2021 12-23-27](https://user-images.githubusercontent.com/82147736/118796213-0ef4be80-b8a4-11eb-83ae-c75504940ac2.gif)

**Comment by OlgaYubil** [comment]
В случае некорректного ввода параметров, должны устанавливаться дефолтные настройки

![GIF 19 05 2021 12-26-35](https://user-images.githubusercontent.com/82147736/118796241-174cf980-b8a4-11eb-9a58-dda679bcba5c.gif)

![GIF 19 05 2021 12-27-46](https://user-images.githubusercontent.com/82147736/118796275-20d66180-b8a4-11eb-8c76-a8bce4ef7a99.gif)

**Comment by OlgaYubil** [comment]
С такими настройками невозможно выбрать максимальное значение. И что такое 0, почему я могу выбрать значение, не удовлетворяющее шагу слайдера?

![GIF 29 05 2021 21-27-28](https://user-images.githubusercontent.com/82147736/120084684-eb6b1880-c0da-11eb-840f-4f645339e26c.gif)

**Comment by victordesyatkin** [comment]
Согласно нового значения шага 3, последнее отображаемое значение 8, далее 8 + 3 = 11 - значение, удовлетворяющее шагу, которое можно выбрать, но 11 не отображается так как выходит за границы максимального значения 10. Значение 10 не отображается и его нельзя выбрать потому что есть шаг 3. Выбирать, можно только значения удовлетворяющие шагу. Отметка шкалы со значением 0 это values для mark, по умолчанию для демонстрации и его можно отключить в панели - это дополнительная опция (API -> mark -> values?: number[] - дополнительные значения отметок шкалы отображаются внезависимости от значения step). Отсчет значений с шагом ведется от минимального значения, если необходимо и правильно добавить отображение минимального и максимального значения и/или возможность их выбора в любом случае (как значение не удовлетворяющее шагу), то конечно же добавлю этот функционал.

**Comment by OlgaYubil** [comment]
Минимальное и максимальное значения должны отображаться и должна быть возможность их выбора вне зависимости от шага, добавь пожалуйста этот функционал.

**Comment by OlgaYubil** [comment]
При отрицательном минимальном значении не всегда возможно установить шаг

![GIF 04 06 2021 10-45-03](https://user-images.githubusercontent.com/82147736/120765578-0813b000-c522-11eb-96dd-4537052d7d27.gif)

**Comment by OlgaYubil** [comment]
![GIF 14 06 2021 22-46-33](https://user-images.githubusercontent.com/82147736/121952328-c0342a80-cd64-11eb-9d52-a522d1ac4f8c.gif)

**Comment by OlgaYubil** [comment]
Вручную ввести отрицательное значение не получается

![GIF 14 06 2021 22-51-35](https://user-images.githubusercontent.com/82147736/121952365-cd511980-cd64-11eb-92d5-f8c70de4d071.gif)

**Comment by OlgaYubil** [comment]
При выставлении начального/конечного значения все же ожидается, что шкала перерисуется в соответствии с минимальным/максимальным значением и шагом, а не просто отсечки добавятся.

![GIF 21 06 2021 11-08-27](https://user-images.githubusercontent.com/82147736/122737119-657d6000-d289-11eb-925c-85ae9f9b6cf0.gif)

**Comment by OlgaYubil** [comment]
![GIF 25 06 2021 20-52-20](https://user-images.githubusercontent.com/82147736/123470391-00b16500-d5fd-11eb-961a-0ef37b7c1001.gif)

**Comment by victordesyatkin** [comment]
В данном случае отметка 100 появляется и остается с учетом настроек конфигурации, самая первая конфигурация отображает максимальное количество настроек. В частности добавлены дополнительные значения отметок (API -> mark -> values), на панели управления в разделе Mark их можно добавлять, редактировать и удалять. Отметка со значением 100 при запуске приложения совпадает с максимальным значением слайдера. После изменения максимального значения слайдера на 105, дополнительное значение отметки 100 уже отображается на слайдере. Далее изменяя шаг мы получаем значение 99 которое отображается рядом с дополнительным значение отметки 100.
